import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import Header from './Header';
import { GridScan } from './GridScan';
import './Samples.css';

function Samples() {
  const navigate = useNavigate();
  const [videos, setVideos] = useState([]);

  useEffect(() => {
    // Hardcoded LDM video for samples
    setVideos([
      {
        id: 'ldm_sample',
        path: '/output/ldm/media/videos/video1/480p15/Video1.mp4',
        title: 'LDM: Latent Diffusion Models',
        description: 'High-Resolution Image Synthesis with Latent Diffusion Models',
        thumbnail: '/output/ldm/media/videos/video1/480p15/Video1.mp4'
      }
    ]);
  }, []);

  const handleVideoClick = (videoId) => {
    navigate(`/video/${videoId}`);
  };

  return (
    <div className="samples-page">
      <div className="grid-container">
        <GridScan
          sensitivity={0.3}
          lineThickness={1}
          linesColor="#888888"
          gridScale={0.08}
          scanColor="#aaaaaa"
          scanOpacity={0.4}
          enablePost={true}
          bloomIntensity={0.3}
          bloomThreshold={0.5}
          chromaticAberration={0.001}
          scanDirection="pingpong"
          scanDuration={1.5}
          scanDelay={0.2}
          lineJitter={0.15}
          noiseIntensity={0.02}
          scanGlow={1.0}
          scanSoftness={0.8}
        />
      </div>

      <Header />

      <div className="samples-content">
        <div className="samples-header">
          <button onClick={() => navigate('/')} className="back-button">
            <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
            </svg>
            Back to Home
          </button>
          <h1>Sample Outputs</h1>
          <p>Explore videos generated by Soren</p>
        </div>

        <div className="videos-grid">
          {videos.map((video) => (
            <div 
              key={video.id} 
              className="video-card"
              onClick={() => handleVideoClick(video.id)}
            >
              <div className="video-thumbnail">
                <video src={video.path} />
                <div className="play-overlay">
                  <svg fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8 5v14l11-7z"></path>
                  </svg>
                </div>
              </div>
              <div className="video-info">
                <h3>{video.title}</h3>
                <p>{video.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default Samples;